
require('plugins')
require('options')
require('simple_setup')
require('telescope_config')
require('cmp_config')
require('copilot_config')
require('mason_config')
require('lsp_config')
require('treesitter_config')
require('globals')
require('keymaps')
require('commands')
require('prettier_config')
require('debuger')
require('null_ls')
require('snips')
require('primeharpoon')
