
require('plugins')
require('simple_setup')
require('telescope_config')
require('cmp_config')
require('copilot_config')
require('mason_config')
require('lsp_config')
require('treesitter_config')
require('globals')
require('options')
require('keymaps')
